package org.scalsys.agile.model;

// Generated Jul 24, 2013 5:29:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contest generated by hbm2java
 */
@Entity
@Table(name = "contest", catalog = "exo_platform_idm")
public class Contest implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long contestId;
	private String contestName;
	private Set<Idea> ideas = new HashSet<Idea>();

	public Contest() {
	}

	public Contest(long contestId, String contestName) {
		this.contestId = contestId;
		this.contestName = contestName;
	}

	public Contest(long contestId, String contestName, Set<Idea> ideas) {
		this.contestId = contestId;
		this.contestName = contestName;
		this.ideas = ideas;
	}

	@Id
	@Column(name = "contest_id", unique = true, nullable = false)
	public long getContestId() {
		return this.contestId;
	}

	public void setContestId(long contestId) {
		this.contestId = contestId;
	}

	@Column(name = "contest_name", nullable = false, length = 100)
	public String getContestName() {
		return this.contestName;
	}

	public void setContestName(String contestName) {
		this.contestName = contestName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contest")
	public Set<Idea> getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set<Idea> ideas) {
		this.ideas = ideas;
	}

}
