package org.scalsys.agile.model;

// Generated Jul 23, 2013 11:53:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdeaSubcategory generated by hbm2java
 */
@Entity
@Table(name = "idea_subcategory", catalog = "exo_platform_idm")
public class IdeaSubcategory implements java.io.Serializable {

	private long subcatagoryId;
	private IdeaCategory ideaCategory;
	private String name;
	private Set ideas = new HashSet(0);

	public IdeaSubcategory() {
	}

	public IdeaSubcategory(long subcatagoryId, IdeaCategory ideaCategory,
			String name) {
		this.subcatagoryId = subcatagoryId;
		this.ideaCategory = ideaCategory;
		this.name = name;
	}

	public IdeaSubcategory(long subcatagoryId, IdeaCategory ideaCategory,
			String name, Set ideas) {
		this.subcatagoryId = subcatagoryId;
		this.ideaCategory = ideaCategory;
		this.name = name;
		this.ideas = ideas;
	}

	@Id
	@Column(name = "subcatagory_id", unique = true, nullable = false)
	public long getSubcatagoryId() {
		return this.subcatagoryId;
	}

	public void setSubcatagoryId(long subcatagoryId) {
		this.subcatagoryId = subcatagoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catagory_id", nullable = false)
	public IdeaCategory getIdeaCategory() {
		return this.ideaCategory;
	}

	public void setIdeaCategory(IdeaCategory ideaCategory) {
		this.ideaCategory = ideaCategory;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaSubcategory")
	public Set getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set ideas) {
		this.ideas = ideas;
	}

}
