package org.scalsys.agile.model;

// Generated Jul 24, 2013 5:29:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdeaCategory generated by hbm2java
 */
@Entity
@Table(name = "idea_category", catalog = "exo_platform_idm")
public class IdeaCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long categoryId;
	private String categoryName;
	private Set<Idea> ideas = new HashSet<Idea>();
	private Set<IdeaSubcategory> ideaSubcategories = new HashSet<IdeaSubcategory>();

	public IdeaCategory() {
	}

	public IdeaCategory(long categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	public IdeaCategory(long categoryId, String categoryName, Set<Idea> ideas,
			Set<IdeaSubcategory> ideaSubcategories) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.ideas = ideas;
		this.ideaSubcategories = ideaSubcategories;
	}

	@Id
	@Column(name = "category_id", unique = true, nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", nullable = false, length = 70)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaCategory")
	public Set<Idea> getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set<Idea> ideas) {
		this.ideas = ideas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaCategory")
	public Set<IdeaSubcategory> getIdeaSubcategories() {
		return this.ideaSubcategories;
	}

	public void setIdeaSubcategories(Set<IdeaSubcategory> ideaSubcategories) {
		this.ideaSubcategories = ideaSubcategories;
	}

}
