package org.scalsys.agile.model;

// Generated Jul 24, 2013 5:29:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdeaSubcategory generated by hbm2java
 */
@Entity
@Table(name = "idea_subcategory", catalog = "exo_platform_idm")
public class IdeaSubcategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long subcategoryId;
	private IdeaCategory ideaCategory;
	private String name;
	private Set<Idea> ideas = new HashSet<Idea>();

	public IdeaSubcategory() {
	}

	public IdeaSubcategory(long subcategoryId, IdeaCategory ideaCategory,
			String name) {
		this.subcategoryId = subcategoryId;
		this.ideaCategory = ideaCategory;
		this.name = name;
	}

	public IdeaSubcategory(long subcategoryId, IdeaCategory ideaCategory,
			String name, Set<Idea> ideas) {
		this.subcategoryId = subcategoryId;
		this.ideaCategory = ideaCategory;
		this.name = name;
		this.ideas = ideas;
	}

	@Id
	@Column(name = "subcategory_id", unique = true, nullable = false)
	public long getSubcategoryId() {
		return this.subcategoryId;
	}

	public void setSubcategoryId(long subcategoryId) {
		this.subcategoryId = subcategoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public IdeaCategory getIdeaCategory() {
		return this.ideaCategory;
	}

	public void setIdeaCategory(IdeaCategory ideaCategory) {
		this.ideaCategory = ideaCategory;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaSubcategory")
	public Set<Idea> getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set<Idea> ideas) {
		this.ideas = ideas;
	}

}
